[build]
  command = "git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter && export PATH=\"$PATH:$(pwd)/_flutter/bin\" && flutter build web --release"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "stable"
